#!/usr/bin/env bash
open /Applications/Postgres.app
unlink /tmp/bitfinexUSD.csv
wget -O /tmp/bitfinexUSD.csv.gz http://api.bitcoincharts.com/v1/csv/bitfinexUSD.csv.gz
gunzip /tmp/bitfinexUSD.csv.gz
time psql btc < ~/prj/csv/btc/bitfinex.sql
unlink /tmp/bitfinexUSD.csv
mv /tmp/BTCUSD.csv ~/prj/csv/data/btcusd_bitfinex.csv
