#!/usr/bin/env bash
open /Applications/Postgres.app
unlink /tmp/bitstampUSD.csv
wget -O /tmp/bitstampUSD.csv.gz http://api.bitcoincharts.com/v1/csv/bitstampUSD.csv.gz
gunzip /tmp/bitstampUSD.csv.gz
time psql btc < ~/prj/csv/btc/bitstamp.sql
unlink /tmp/bitstampUSD.csv
mv /tmp/BTCUSD.csv ~/prj/csv/data/btcusd_bitstamp.csv
